---
system_update_reboot_if_needed: false
# Globálne DevOps premenné pre celý server
base_docker_path: "/opt/docker"
appdata_path: "{{ base_docker_path }}/app-data"
# Globálne nastavenia
timezone: "Europe/Bratislava"
# Tu neskôr zadefinujeme aj cesty k filmom/seriálom na disku
# media_movies_path: "/mnt/storage/movies"
# Sieťové nastavenia
lan_subnet: "192.168.0.0/24"
docker_subnet: "172.16.0.0/12"

# Systémové balíky pre bootstrap
base_packages:
  - qemu-guest-agent
  - ufw
  - curl
  - git
  - htop
  - iotop
  - ca-certificates
  - gnupg

# Správa diskových ciest
storage_ssd_path: "/mnt/ssd"
storage_hdd_path: "/mnt/hdd8T"
