---
ansible_user: sysadmin
node_env: staging

# Disk paths for staging (e.g., if staging doesn't have a second HDD, map to temporary directories)
storage_ssd_path: "/mnt/ssd"
storage_hdd_path: "/mnt/hdd8T"

# Physical disks do not need to be present in staging
mount_physical_disks: false
