[staging]
staging-vm ansible_host=192.168.122.233 ansible_user=ubuntu
[staging:vars]
# Disables host key checking ONLY for this temporary KVM test VM
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
