[staging]
staging-vm ansible_host=192.168.122.230 ansible_user=ubuntu

[staging:vars]
# Vypne kontrolu kľúčov IBA pre dočasnú testovaciu VM v KVM
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
