[homelab]
gaia-server ansible_host=192.168.1.100

[homelab:vars]
ansible_user=gaia

[staging]
staging-node-01 ansible_host=192.168.122.97 ansible_user=sysadmin

[all:vars]
ansible_python_interpreter=/usr/bin/python3
